# Generated by Django 5.0 on 2025-04-14 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='poll_id',
            field=models.ForeignKey(default='1c3c6f9f-d3e4-495a-aea8-b03e2c023f8b', on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e04845c-338f-4802-be61-99246a45a4ec'), primary_key=True, serialize=False),
        ),
    ]
