# Generated by Django 5.0 on 2025-04-14 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_poll_id_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='poll',
            field=models.ForeignKey(default='19185178-0750-4706-ae93-444ffbd1c211', on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a260575-fe66-484b-8609-f94497c98c6b'), primary_key=True, serialize=False),
        ),
    ]
